config/routes.rb
Researcher::Application.routes.draw do
  get "games/launcher"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "welcome/index"

  devise_for :users
  match '/launch/:id', :to=> "projects#launch_page", :as=>"launch_page"
  match '/game/launch/:id', :to=> "games#launcher", :as=>"launcher"
  match '/game/:id/(:gnode_id)', :to=> "games#game_screen", :as=>"game_screen"
  match '/note_selection', :to=> "games#note_selection", :as=>"note_selection"
  match '/comparison_selection', :to=> "games#comparison_selection", :as=>"comparison_selection"
  match '/image_selection', :to=> "answers#selection", :as=>"image_selection"
  match '/thankyou', :to=> "welcome#thankyou", :as=>"thankyou"
  match '/reset_game/:id', :to=> "games#reset_game", :as=>"reset_game"

     resources :selections
     resources :gnodes
     resources :gpaths
     resources :answers

root:to=>'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :game_type_id, :project_id, :gnodes_attributes, :avatar, :marquee, :sequence, :markup
  belongs_to :game_type
  belongs_to :project
  has_many :gnodes, :dependent => :destroy
  has_many :scores, :dependent => :destroy
  accepts_nested_attributes_for :gnodes, :reject_if => proc { |attributes| attributes.all? { |k, v| v.blank? } }
  has_attached_file :avatar, :styles => {
      :original => {
          :geometry => "1366x840>"
      },
      :thumbnail => {
          :geometry => "80x80"
      }
  }
  has_attached_file :marquee, :styles => {
      :original => {
          :geometry => "1366x840>"
      },
      :thumbnail => {
          :geometry => "80x80"
      }
  }

  after_create :create_scores

  def create_scores
    self.project.project_users.each do |project_user|
      Score.create!(:game_id=>self.id,:user_id=>project_user.user.id,:value=>0)
    end
  end

end

app/models/game_type.rb
class GameType < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :games, :dependent => :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def launcher
    @game=Game.find(params[:id])
  end

  def game_screen
    @game=Game.find(params[:id])
    @user=current_user
    @next_game=@game.project.games.where('sequence=?', @game.sequence+1).first unless @game.project.games.count==@game.sequence

    if %w(Campaign AntiCampaign).include? @game.game_type.name
      @title=@game.markup.split('||')[0]
      @catchphrase=@game.markup.split('||')[1]
      @body=@game.markup.split('||')[2]
      @answers=Array.new
      @game.gnodes.each_with_index do |gnode, index|
        if Answer.find_by_gnode_id_and_user_id(gnode.id, @user.id).blank?
          @answers[index]=Answer.create!(:gnode_id => gnode.id, :user_id => @user.id)
        else
          @answers[index]= Answer.find_by_gnode_id_and_user_id(gnode.id, @user.id)
        end
      end
    else
      @gnode=Gnode.find(params[:gnode_id])
    end

    @selection=Selection.new
  end

  def note_selection
    @gpath=Gpath.find_by_name(params[:selection])

    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank? and @gpath.selections.where('user_id=?', current_user.id).blank?
      Selection.create!(:user_id => current_user.id, :gpath_id => @gpath.id)
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      @score.value+=@gpath.markup.to_i
      @score.save
    end
    if @gpath.gnode.gpaths.map { |gp| gp.selections.where('user_id=?', current_user.id).count }.sum==3 and @gpath.gnode.completions.where('user_id=?', current_user.id).blank?
      Completion.create!(:user_id => current_user.id, :gnode_id => @gpath.gnode.id)
    end
    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank?
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|0"
    elsif @gpath.gnode.markup.blank?
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|-1"
    else
      @gnext=@gpath.gnode.game.gnodes.where('name=?', @gpath.gnode.markup).first
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|#{@gnext.id}"
    end
  end

  def comparison_selection
    @gnode=Gnode.find(params[:nodeadd][0])
    @gpath=@gnode.gpaths.where('name=?',params[:selection][0]).first

    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank? and @gpath.selections.where('user_id=?', current_user.id).blank?
      Selection.create!(:user_id => current_user.id, :gpath_id => @gpath.id)
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      @score.value+=@gpath.markup.to_i
      @score.save
      Completion.create!(:user_id => current_user.id, :gnode_id => @gpath.gnode.id)
    end
    @totalscore=@gpath.gnode.game.project.games.map { |g| g.scores.where('user_id=?', current_user.id).first.value }.sum
    if @gpath.gnode.markup.blank?
      render :text => "#{@gpath.next_id.to_s}|#{@totalscore}|-1"
    else
      render :text => "#{@gnode.markup}|#{@totalscore}|0"
    end
  end

  def reset_game
    @game=Game.find(params[:id])
    @user=User.find(current_user.id)
    @score=Score.where('user_id=?', @user.id).where('game_id=?', @game.id).first
    @score.value=0
    @score.save
    Completion.where('user_id=?', @user.id).each do |completion|
      if @game.gnodes.include?(completion.gnode)
        completion.destroy
      end
    end
    @game.gnodes.each do |gnode|
      gnode.answers.where('user_id=?', @user.id).each do |answer|
        answer.destroy
      end
      gnode.gpaths.each do |gpath|
        gpath.selections.where('user_id=?', @user.id).each do |selection|
          selection.destroy
        end
      end
    end

  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/game_screen.html.erb
<% case @game.game_type.name %>
<% when "Family Feud" %>
    <%= render :partial => '/games/engines/family_feud' %>
<% when "Comparisons" %>
    <%= render :partial => '/games/engines/comparisons' %>
<% when "Campaign" %>
    <%= render :partial => '/games/engines/campaign' %>
<% when "AntiCampaign" %>
    <%= render :partial => '/games/engines/anticampaign' %>
<% end %>

app/views/games/launcher.html.erb
<%= content_for :head do %>
    <style type="text/css">
        a, a:link, a:visited, .btn {
            color: black;
            font-size: 18px;
            font-weight: bold;
        }

        body {
            margin: 0 auto;
            margin-top: 40px;
            width: 960px;
            background: url('/assets/curtain.jpg') no-repeat;
            background-size: 100% 100%;
            height: 600px;
            overflow: hidden;
        }
    </style>
<% end %>
<%= image_tag @game.marquee.url(:original), :style => "margin-left:230px;; margin-top:110px;" %>
<div style="margin-left: 340px;">
  <a class="btn btn-danger btn-large" data-backdrop="static" data-toggle="modal" href="#knowmore" >How to Play</a>
  <a class="btn btn-warning btn-large" href="<%= game_screen_path(@game, @game.gnodes.first) %>" >Start the Game</a>
</div>

<div class="modal hide fade" id="knowmore">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>

    <h3>Know More</h3>
  </div>
  <div class="modal-body">
    <%= raw @game.game_type.description %>
  </div>
  <div class="modal-footer">
    <a href="#" class="close" data-dismiss="modal">Close</a>
  </div>
</div>