config/routes.rb
Researcher::Application.routes.draw do
  get "games/launcher"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "welcome/index"

  devise_for :users
  match '/launch/:id', :to=> "projects#launch_page", :as=>"launch_page"
  match '/game/launch/:id', :to=> "games#launcher", :as=>"launcher"
  match '/game/:id/(:gnode_id)', :to=> "games#game_screen", :as=>"game_screen"
  match '/note_selection', :to=> "games#note_selection", :as=>"note_selection"
  match '/comparison_selection', :to=> "games#comparison_selection", :as=>"comparison_selection"
  match '/image_selection', :to=> "answers#selection", :as=>"image_selection"
  match '/thankyou', :to=> "welcome#thankyou", :as=>"thankyou"
  match '/reset_game/:id', :to=> "games#reset_game", :as=>"reset_game"

     resources :selections
     resources :gnodes
     resources :gpaths
     resources :answers

root:to=>'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :game_type_id, :project_id, :gnodes_attributes, :avatar, :marquee, :sequence, :markup
  belongs_to :game_type
  belongs_to :project
  has_many :gnodes, :dependent => :destroy
  has_many :scores, :dependent => :destroy
  accepts_nested_attributes_for :gnodes, :reject_if => proc { |attributes| attributes.all? { |k, v| v.blank? } }
  has_attached_file :avatar, :styles => {
      :original => {
          :geometry => "1366x840>"
      },
      :thumbnail => {
          :geometry => "80x80"
      }
  }
  has_attached_file :marquee, :styles => {
      :original => {
          :geometry => "1366x840>"
      },
      :thumbnail => {
          :geometry => "80x80"
      }
  }

  after_create :create_scores

  def create_scores
    self.project.project_users.each do |project_user|
      Score.create!(:game_id=>self.id,:user_id=>project_user.user.id,:value=>0)
    end
  end

end

app/models/game_type.rb
class GameType < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :games, :dependent => :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def launcher
    @game=Game.find(params[:id])
  end

  def game_screen
    @game=Game.find(params[:id])
    @user=current_user
    @next_game=@game.project.games.where('sequence=?', @game.sequence+1).first unless @game.project.games.count==@game.sequence

    if %w(Campaign AntiCampaign).include? @game.game_type.name
      @title=@game.markup.split('||')[0]
      @catchphrase=@game.markup.split('||')[1]
      @body=@game.markup.split('||')[2]
      @answers=Array.new
      @game.gnodes.each_with_index do |gnode, index|
        if Answer.find_by_gnode_id_and_user_id(gnode.id, @user.id).blank?
          @answers[index]=Answer.create!(:gnode_id => gnode.id, :user_id => @user.id)
        else
          @answers[index]= Answer.find_by_gnode_id_and_user_id(gnode.id, @user.id)
        end
      end
    else
      @gnode=Gnode.find(params[:gnode_id])
    end

    @selection=Selection.new
  end

  def note_selection
    @gpath=Gpath.find_by_name(params[:selection])

    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank? and @gpath.selections.where('user_id=?', current_user.id).blank?
      Selection.create!(:user_id => current_user.id, :gpath_id => @gpath.id)
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      @score.value+=@gpath.markup.to_i
      @score.save
    end
    if @gpath.gnode.gpaths.map { |gp| gp.selections.where('user_id=?', current_user.id).count }.sum==3 and @gpath.gnode.completions.where('user_id=?', current_user.id).blank?
      Completion.create!(:user_id => current_user.id, :gnode_id => @gpath.gnode.id)
    end
    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank?
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|0"
    elsif @gpath.gnode.markup.blank?
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|-1"
    else
      @gnext=@gpath.gnode.game.gnodes.where('name=?', @gpath.gnode.markup).first
      render :text => "#{@gpath.next_id.to_s}|#{@gpath.markup}|#{@score.value}|#{@gnext.id}"
    end
  end

  def comparison_selection
    @gnode=Gnode.find(params[:nodeadd][0])
    @gpath=@gnode.gpaths.where('name=?',params[:selection][0]).first

    if @gpath.gnode.completions.where('user_id=?', current_user.id).blank? and @gpath.selections.where('user_id=?', current_user.id).blank?
      Selection.create!(:user_id => current_user.id, :gpath_id => @gpath.id)
      @score=Score.find_by_game_id_and_user_id(@gpath.gnode.game.id, current_user.id)
      @score.value+=@gpath.markup.to_i
      @score.save
      Completion.create!(:user_id => current_user.id, :gnode_id => @gpath.gnode.id)
    end
    @totalscore=@gpath.gnode.game.project.games.map { |g| g.scores.where('user_id=?', current_user.id).first.value }.sum
    if @gpath.gnode.markup.blank?
      render :text => "#{@gpath.next_id.to_s}|#{@totalscore}|-1"
    else
      render :text => "#{@gnode.markup}|#{@totalscore}|0"
    end
  end

  def reset_game
    @game=Game.find(params[:id])
    @user=User.find(current_user.id)
    @score=Score.where('user_id=?', @user.id).where('game_id=?', @game.id).first
    @score.value=0
    @score.save
    Completion.where('user_id=?', @user.id).each do |completion|
      if @game.gnodes.include?(completion.gnode)
        completion.destroy
      end
    end
    @game.gnodes.each do |gnode|
      gnode.answers.where('user_id=?', @user.id).each do |answer|
        answer.destroy
      end
      gnode.gpaths.each do |gpath|
        gpath.selections.where('user_id=?', @user.id).each do |selection|
          selection.destroy
        end
      end
    end

  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/engines/_anticampaign.html.erb
<%= content_for :head do %>
    <script type="text/javascript">
        $(function () {

            $.ajaxSetup({
                beforeSend:function (xhr) {
                    xhr.setRequestHeader('X-CSRF-Token',
                            $('meta[name="csrf-token"]').attr('content'));
                }
            });

            $('#slider').anythingSlider({
                buildArrows:false,
                delay:2000,
                onSlideComplete:function (slider) {
                    var data = {selection:[], answer:[]};
                    data["selection"].push(slider.currentPage);
                    data["answer"].push(<%= @answers[3].id %>);
                    $.ajax({
                        url:"<%= image_selection_path %>",
                        type:"post",
                        data:JSON.stringify(data),
                        contentType:"application/json",
                        success:function (returning_data) {
                        }
                    });

                }

            });
            $('#slider2').anythingSlider({
                buildArrows:false,
                delay:2000,
                onSlideComplete:function (slider) {
                    var data = {selection:[], answer:[]};
                    data["selection"].push(slider.currentPage);
                    data["answer"].push(<%= @answers[4].id %>);
                    $.ajax({
                        url:"<%= image_selection_path %>",
                        type:"post",
                        data:JSON.stringify(data),
                        contentType:"application/json",
                        success:function (returning_data) {
                        }
                    });

                }

            });

        })
    </script>
    <style>
        #slider {
            width: 240px;
            height: 180px;

        }

            /* images with caption */
        #slider img {
            width: 180px;
            height: 280px;
            border-radius: 10px;
        }

            /* position the panels so the captions appear correctly */
        #slider .panel {
            position: relative;
        }

            /* captions */
        #slider .caption-top, #slider .caption-right,
        #slider .caption-bottom, #slider .caption-left {
            background: #000;
            color: #fff;
            padding: 10px;
            margin: 0;
            position: relative;
            z-index: 10;
            opacity: .8;
            filter: alpha(opacity = 80);
        }

            /*** Set Slider dimensions here! Version 1.7+ ***/
        #slider {
            /*background: white;*/
            /*width: 300px;*/
            /*height: 300px;*/
            list-style: none;
        }

        #slider li {
            position: relative;
        }


    </style>

    <style>
        #slider2 {
            width: 100px;
            height: 100px;

        }

            /* images with caption */
        #slider2 img {
            width: 80px;
            height: 80px;
            border-radius: 10px;
        }

            /* position the panels so the captions appear correctly */
        #slider2 .panel {
            position: relative;
        }

            /* captions */
        #slider2 .caption-top, #slider2 .caption-right,
        #slider2 .caption-bottom, #slider2 .caption-left {
            background: #000;
            color: #fff;
            padding: 10px;
            margin: 0;
            position: relative;
            z-index: 10;
            opacity: .8;
            filter: alpha(opacity = 80);
        }

            /*** Set Slider dimensions here! Version 1.7+ ***/
        #slider2 {
            /*background: white;*/
            /*width: 300px;*/
            /*height: 300px;*/
            list-style: none;
        }

        #slider2 li {
            position: relative;
        }


    </style>


    <style type="text/css">

        body {
            background: transparent;
        }

        #poster {
            margin-top: 20px;
            position: relative;
            float: right;
            width: 500px;
            height: 560px;
            border: 6px solid black;
            border-radius: 10px;
            background: black;
        }

        .section {
            position: absolute;
            padding: 10px;
        }

        #main {
            left: 0px;
            top: 10px;
            width: 100%;
            height: 400px;
            background-image: url('/assets/NO.jpg');
            background-size: 100% 100%;
        }

        #title {
            left: -20px;
            bottom: 50px;
            width: 440px;
            height: 80px;
        }

        #main_pic {
            right: 90px;
            top: 15px;
            width: 220px;
            height: 340px;
        }

        #detailed {
            left: 30px;
            top: 190px;
            width: 350px;
            height: 120px;
            background: #ff8b4c;
            border: solid 1px black;
            border-radius: 10px;
            padding-top: 30px;
            padding-left: 10px;
            padding-right: 15px;
        }

        #protest {
            position: absolute;
            top: 100px;
            left: 20px;
            font-size: 40px;
            color: white;
            font-weight: bolder;
        }

        #done {
            position: absolute;
            bottom: 50px;
            right: 60px;
            font-size: 30px;
            color: white;
            font-weight: bolder;
        }

    </style>
<% end %>

<%= link_to "Done", "/game/6", :id=>"done", :class=>"btn btn-danger btn-large" %>

<div id="left" style="float:left;width:350px;">
  <br>
  <table>
    <tr>
      <td style="width:170px;"><%= image_tag "host3.png", :style => "width:150px;" %></td>
      <td style="color:white;font-size: 11px">
        <h1 style="float: left;color: white;font-weight: bolder;"><%= @game.game_type.name %></h1>
        <br>
        <br>
        <br>
        They are launching the product described below in the market. We don't like it. Can you help us tell the world
        why it isn't a good idea?
        <br>
        <br>
        Build the poster on the left to make your point. Click on start to rotate the pictures, stop to select. Then explain your stance through the points, title and slogan. If the poster is one of the top ten
        picks of our team, we will add 350 points to your score.

        <br>
        <br>
      </td>
    </tr>
    <tr style="border: solid 2px black;background: #f2cb50;border-radius: 10px;">
      <td colspan="2" style="padding: 20px;border-radius: 10px;">
        <h1>
          <%= @title %>
          <%= image_tag @game.avatar.url(:original), :style => "width:50px;vertical-align:middle;float:right;" %></h1>
        <%= @catchphrase %>
      </td>
    </tr>
    <tr style="height:10px;"></tr>
    <tr style="border: solid 2px black;background: #ffd6a6;border-radius: 10px;">
      <td colspan="2" style="padding: 10px;border-radius: 10px;text-align: center;font-size: 18px;">
        <%= raw @body %>
      </td>
    </tr>
  </table>


  <p style="width:270px;float: left;">

  </p>
</div>
<div id="poster">
  <div id="main">
    <div id="protest">
      <%= image_tag "protesters.png", :style => "width:200px;" %>
    </div>
    <div id="detailed" class="section">
      <%= editable_field @answers[2], :matter, :type => 'textarea', :placeholder => "Click to add your anti-campaign points", :onblur => 'submit', :rows => "5" %>
    </div>
    <div id="main_pic" class="section">
      <ul id="slider">
        <li><%= image_tag "bad/1.jpg" %></li>
        <li><%= image_tag "bad/2.jpg" %></li>
        <li><%= image_tag "bad/3.jpg" %></li>
        <li><%= image_tag "bad/4.jpg" %></li>
        <li><%= image_tag "bad/5.jpg" %></li>
        <li><%= image_tag "bad/6.jpg" %></li>
        <li><%= image_tag "bad/7.png" %></li>
        <li><%= image_tag "bad/8.jpg" %></li>
        <li><%= image_tag "bad/9.jpg" %></li>
        <li><%= image_tag "bad/10.jpg" %></li>
        <li><%= image_tag "bad/11.jpg" %></li>
        <li><%= image_tag "bad/12.jpg" %></li>
        <li><%= image_tag "bad/13.jpg" %></li>

      </ul>
    </div>
    <div id="title" class="section">
      <div style="float:left;margin-right: 10px;">
        <ul id="slider2">
          <li><%= image_tag "emoticons/1.png" %></li>
          <li><%= image_tag "emoticons/2.png" %></li>
          <li><%= image_tag "emoticons/3.png" %></li>
          <li><%= image_tag "emoticons/4.png" %></li>
          <li><%= image_tag "emoticons/5.png" %></li>
          <li><%= image_tag "emoticons/6.png" %></li>
          <li><%= image_tag "emoticons/7.png" %></li>
          <li><%= image_tag "emoticons/8.png" %></li>
          <li><%= image_tag "emoticons/9.png" %></li>
          <li><%= image_tag "emoticons/10.png" %></li>
          <li><%= image_tag "emoticons/11.png" %></li>
        </ul>
      </div>
      <div style="float:left;margin-left: -20px;margin-top: 20px;">
        <h2 style="color:white;"><%= editable_field @answers[0], :matter, :placeholder => "Click to add a title", :onblur => 'submit' %></h2>

        <h3 style="color:white;"><%= editable_field @answers[1], :matter, :placeholder => "Click to add a slogan", :onblur => 'submit' %></h3>
      </div>
    </div>

  </div>
</div>

app/views/games/engines/_campaign.html.erb
<%= content_for :head do %>
    <script type="text/javascript">
        $(function () {

            $.ajaxSetup({
                beforeSend:function (xhr) {
                    xhr.setRequestHeader('X-CSRF-Token',
                            $('meta[name="csrf-token"]').attr('content'));
                }
            });

            $('#slider').anythingSlider({
                buildArrows:false,
                delay:2000,
                onSlideComplete:function (slider) {
                    var data = {selection:[], answer:[]};
                    data["selection"].push(slider.currentPage);
                    data["answer"].push(<%= @answers[3].id %>);
                    $.ajax({
                        url:"<%= image_selection_path %>",
                        type:"post",
                        data:JSON.stringify(data),
                        contentType:"application/json",
                        success:function (returning_data) {
                        }
                    });

                }

            });
            $('#slider2').anythingSlider({
                buildArrows:false,
                delay:2000,
                onSlideComplete:function (slider) {
                    var data = {selection:[], answer:[]};
                    data["selection"].push(slider.currentPage);
                    data["answer"].push(<%= @answers[4].id %>);
                    $.ajax({
                        url:"<%= image_selection_path %>",
                        type:"post",
                        data:JSON.stringify(data),
                        contentType:"application/json",
                        success:function (returning_data) {
                        }
                    });

                }

            });

        })
    </script>
    <style>
        #slider {
            width: 240px;
            height: 180px;

        }

            /* images with caption */
        #slider img {
            width: 180px;
            height: 280px;
            border-radius: 10px;
        }

            /* position the panels so the captions appear correctly */
        #slider .panel {
            position: relative;
        }

            /* captions */
        #slider .caption-top, #slider .caption-right,
        #slider .caption-bottom, #slider .caption-left {
            background: #000;
            color: #fff;
            padding: 10px;
            margin: 0;
            position: relative;
            z-index: 10;
            opacity: .8;
            filter: alpha(opacity = 80);
        }

            /*** Set Slider dimensions here! Version 1.7+ ***/
        #slider {
            /*background: white;*/
            /*width: 300px;*/
            /*height: 300px;*/
            list-style: none;
        }

        #slider li {
            position: relative;
        }


    </style>

    <style>
        #slider2 {
            width: 100px;
            height: 100px;

        }

            /* images with caption */
        #slider2 img {
            width: 80px;
            height: 80px;
            border-radius: 10px;
        }

            /* position the panels so the captions appear correctly */
        #slider2 .panel {
            position: relative;
        }

            /* captions */
        #slider2 .caption-top, #slider2 .caption-right,
        #slider2 .caption-bottom, #slider2 .caption-left {
            background: #000;
            color: #fff;
            padding: 10px;
            margin: 0;
            position: relative;
            z-index: 10;
            opacity: .8;
            filter: alpha(opacity = 80);
        }

            /*** Set Slider dimensions here! Version 1.7+ ***/
        #slider2 {
            /*background: white;*/
            /*width: 300px;*/
            /*height: 300px;*/
            list-style: none;
        }

        #slider2 li {
            position: relative;
        }


    </style>


    <style type="text/css">

        body {
            background: transparent;
        }

        #poster {
            margin-top: 20px;
            position: relative;
            float: right;
            width: 500px;
            height: 560px;
            border: 6px solid black;
            border-radius: 10px;
            background: #f5f5f5;
        }

        .section {
            position: absolute;
            padding: 10px;
        }

        #main {
            left: 0px;
            top: 10px;
            width: 100%;
            height: 400px;
            background-image: url('/assets/yes.jpg');
            background-size: 100% 100%;
        }

        #title {
            left: -20px;
            bottom: 50px;
            width: 440px;
            height: 80px;
        }

        #main_pic {
            right: 90px;
            top: 15px;
            width: 220px;
            height: 340px;
        }

        #detailed {
            left: 30px;
            top: 190px;
            width: 350px;
            height: 120px;
            background: #f7b73c;
            border: solid 1px black;
            border-radius: 10px;
            padding-top: 30px;
            padding-left: 10px;
            padding-right: 15px;
        }

        #protest {
            position: absolute;
            top: 10px;
            left: 20px;
            font-size: 40px;
            color: white;
            font-weight: bolder;
        }

        #done {
            position: absolute;
            bottom: 50px;
            right: 60px;
            font-size: 30px;
            color: white;
            font-weight: bolder;
        }

    </style>
<% end %>

<%= link_to "Done", "/thankyou", :id => "done", :class => "btn btn-danger btn-large" %>

<div id="left" style="float:left;width:350px;">
  <br>
  <table>
    <tr>
      <td style="width:170px;"><%= image_tag "host4.png", :style => "width:150px;" %></td>
      <td style="color:white;font-size: 11px">
        <h1 style="float: left;color: white;font-weight: bolder;"><%= @game.game_type.name %></h1>
        <br>
        <br>
        <br>
        We are launching this product in the market. Can you help us tell the world why it is great?
        <br>
        <br>
        Build the poster on the left to make your point. Click on start to rotate the pictures, stop to select. Then
        explain your stance through the points, title and slogan. If the poster is one of the top ten
        picks of our team, you will score 350 points.
        <br>
        <br>
      </td>
    </tr>
    <tr style="border: solid 2px black;background: #f2cb50;border-radius: 10px;">
      <td colspan="2" style="padding: 20px;border-radius: 10px;">
        <h1>
          <%= @title %>
          <%= image_tag @game.avatar.url(:original), :style => "width:50px;vertical-align:middle;float:right;" %></h1>
        <%= @catchphrase %>
      </td>
    </tr>
    <tr style="height:10px;"></tr>
    <tr style="border: solid 2px black;background: #ffd6a6;border-radius: 10px;">
      <td colspan="2" style="padding: 10px;border-radius: 10px;text-align: center;font-size: 18px;">
        <%= raw @body %>
      </td>
    </tr>
  </table>


  <p style="width:270px;float: left;">

  </p>
</div>
<div id="poster">
  <div id="main">
    <div id="protest">
      <%= image_tag "thumbsup.png", :style => "width:200px;" %>
    </div>
    <div id="detailed" class="section">
      <%= editable_field @answers[2], :matter, :type => 'textarea', :placeholder => "Click to add your campaign points", :onblur => 'submit', :rows => "5" %>
    </div>
    <div id="main_pic" class="section">
      <ul id="slider">
        <li><%= image_tag "good/1.jpg" %></li>
        <li><%= image_tag "good/2.jpg" %></li>
        <li><%= image_tag "good/3.jpg" %></li>
        <li><%= image_tag "good/4.jpg" %></li>
        <li><%= image_tag "good/5.gif" %></li>
        <li><%= image_tag "good/6.jpg" %></li>
        <li><%= image_tag "good/7.jpg" %></li>
        <li><%= image_tag "good/8.jpg" %></li>
        <li><%= image_tag "good/9.jpg" %></li>
        <li><%= image_tag "good/10.jpg" %></li>
        <li><%= image_tag "good/11.jpg" %></li>
        <li><%= image_tag "good/12.png" %></li>
        <li><%= image_tag "good/13.jpg" %></li>
        <li><%= image_tag "good/14.jpg" %></li>
        <li><%= image_tag "good/15.jpeg" %></li>
        <li><%= image_tag "good/16.jpg" %></li>
        <li><%= image_tag "good/17.gif" %></li>
      </ul>
    </div>
    <div id="title" class="section">
      <div style="float:left;margin-right: 10px;">
        <ul id="slider2">
          <li><%= image_tag "emoticons/1.png" %></li>
          <li><%= image_tag "emoticons/2.png" %></li>
          <li><%= image_tag "emoticons/3.png" %></li>
          <li><%= image_tag "emoticons/4.png" %></li>
          <li><%= image_tag "emoticons/5.png" %></li>
          <li><%= image_tag "emoticons/6.png" %></li>
          <li><%= image_tag "emoticons/7.png" %></li>
          <li><%= image_tag "emoticons/8.png" %></li>
          <li><%= image_tag "emoticons/9.png" %></li>
          <li><%= image_tag "emoticons/10.png" %></li>
          <li><%= image_tag "emoticons/11.png" %></li>
        </ul>
      </div>
      <div style="float:left;margin-left: -20px;margin-top: 20px;">
        <h2 style="color:black;"><%= editable_field @answers[0], :matter, :placeholder => "Click to add a title", :onblur => 'submit' %></h2>

        <h3 style="color:black;"><%= editable_field @answers[1], :matter, :placeholder => "Click to add a slogan", :onblur => 'submit' %></h3>
      </div>
    </div>

  </div>
</div>

app/views/games/engines/_comparisons.html.erb
<%= content_for :head do %>
    <style type="text/css">
        body {
            margin: 0 auto;
            margin-top: 20px;
            width: 960px;
            /*background: url('/assets/goldbackdrop.jpg') no-repeat;*/
            /*background-size: 100% 100%;*/
            background: transparent;
            height: 600px;
            overflow: hidden;
        }

        a, a:link, a:visited, .btn {
            color: black;
            font-size: 18px;
            font-weight: bold;
        }

        .btn-custom {
            font-size: 24px;
            color: white;
            height: 24px;
            width: 220px;
        }

        #scoreboard {
            margin-left: 40px;
            margin-top: 30px;
            width: 410px;
            height: 120px;

        }

        #scoreboard td {
            padding: 2px;
        }

        .namebox {
            font-size: 14px;
            color: white;
            padding: 10px;
            background: #111;
            width: 120px;

        }

        .pollbox {
            font-size: 18px;
            color: black;
            padding: 10px;
            background: #eee;
            width: 30px;

        }
    </style>

<% end %>
<div style="font-size:48px;width:90%;text-align: right;line-height: 64px;margin-bottom: 20px;color:white;">
  <span style="float:right;">Comparisons</span>

  <div style="background: #ffa500; width:150px; margin-top: 70px;margin-right: -280px;padding:2px;float:right;border-radius: 10px;border: 2px solid black;text-align: center;">
    <h2 id="scorebox">Score:
      <span id="score">
        <%= @game.project.games.map { |g| g.scores.where('user_id=?', current_user.id).first.value }.sum %>
      </span>
    </h2>
  </div>
</div>

<%= image_tag @gnode.avatar.url(:original), :style => "width:500px;float:left;margin-top:-50px" %>
<%= image_tag "host2.png", :style => "float:left;margin-left:-80px;" %>
<div style="float:left;margin-top: -80px;margin-left: 20px;">
  <% @gnode.gpaths.each_with_index do |gpath, index| %>
      <%= link_to gpath.name, "#", :id => "current#{index}", :class => "btn btn-large btn-warning btn-custom choices" %>
  <% end %>
  <%= link_to "Next", "#", :id => "next", :class => "btn btn-large btn-warning btn-custom choices", :style => "display: none" %>

</div>


<script type="text/javascript">
    $(function () {

        $.ajaxSetup({
            beforeSend:function (xhr) {
                xhr.setRequestHeader('X-CSRF-Token',
                        $('meta[name="csrf-token"]').attr('content'));
            }
        });

        $('.choices').click(function () {
            add_response($(this).text(),<%= @gnode.id %>);
        });
    });

    function add_response(name,pp) {
        var data = {selection:[], nodeadd:[]};
        data["selection"].push(name);
        data["nodeadd"].push(pp);
        $.ajax({
            url:"<%= comparison_selection_path %>",
            type:"post",
            data:JSON.stringify(data),
            contentType:"application/json",
            success:function (returning_data) {
                var nextid = returning_data.split("|")[0];
                var score = returning_data.split("|")[1];
                var toggler = returning_data.split("|")[2];
                $('#score').html(score);
                $('.choices').hide();
                $('#next').show();
                if (toggler == "0") {
                    $('#next').attr("href", "/game/launch/" + nextid);
                } else {
                    $('#next').attr("href", "/game/<%= @game.id %>/" + nextid);
                }
                $('#next').animate({
                    width:"270px",
                    height:"60px",
                    fontSize:"48px",
                    color:"white"
                }, 2000);
            }
        });
    }
</script>