config/routes.rb
Researcher::Application.routes.draw do
  get "games/launcher"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "welcome/index"

  devise_for :users
  match '/launch/:id', :to=> "projects#launch_page", :as=>"launch_page"
  match '/game/launch/:id', :to=> "games#launcher", :as=>"launcher"
  match '/game/:id/(:gnode_id)', :to=> "games#game_screen", :as=>"game_screen"
  match '/note_selection', :to=> "games#note_selection", :as=>"note_selection"
  match '/comparison_selection', :to=> "games#comparison_selection", :as=>"comparison_selection"
  match '/image_selection', :to=> "answers#selection", :as=>"image_selection"
  match '/thankyou', :to=> "welcome#thankyou", :as=>"thankyou"
  match '/reset_game/:id', :to=> "games#reset_game", :as=>"reset_game"

     resources :selections
     resources :gnodes
     resources :gpaths
     resources :answers

root:to=>'welcome#index'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  attr_accessible :gpath_id, :user_id
  belongs_to :gpath
  belongs_to :user
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @selections }
    end
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
    @selection = Selection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/new
  # GET /selections/new.json
  def new
    @selection = Selection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/1/edit
  def edit
    @selection = Selection.find(params[:id])
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(params[:selection])

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: 'Selection was successfully created.' }
        format.json { render json: @selection, status: :created, location: @selection }
      else
        format.html { render action: "new" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /selections/1
  # PUT /selections/1.json
  def update
    @selection = Selection.find(params[:id])

    respond_to do |format|
      if @selection.update_attributes(params[:selection])
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection = Selection.find(params[:id])
    @selection.destroy

    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :gpath_id %><br />
    <%= f.number_field :gpath_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <tr>
    <th>User</th>
    <th>Gpath</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @selections.each do |selection| %>
  <tr>
    <td><%= selection.user_id %></td>
    <td><%= selection.gpath_id %></td>
    <td><%= link_to 'Show', selection %></td>
    <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
    <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @selection.user_id %>
</p>

<p>
  <b>Gpath:</b>
  <%= @selection.gpath_id %>
</p>


<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>